osx_image: xcode8.2
language: objective-c
install:
- gem install cocoapods -v 1.1.1 --no-document

before_script:
- cd Example
- pod install

xcode_workspace: Popover.xcworkspace
xcode_scheme: PopoverExample
xcode_sdk: iphonesimulator
